services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bank_db}
      POSTGRES_USER: ${POSTGRES_USER:-bank_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bank_pass}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata:
