# Generated by Django 5.2.5 on 2025-08-22 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, unique=True)),
                ('type', models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings')], max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=8)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='customers.customer')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
