# Generated by Django 5.2.5 on 2025-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('TRANSFER', 'Virement'), ('DEPOSIT', 'Dépôt'), ('WITHDRAW', 'Retrait')], max_length=16),
        ),
    ]
