# Generated by Django 5.2.5 on 2025-08-23 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_account_status'),
        ('transactions', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(upload_to='invoices/')),
                ('status', models.CharField(choices=[('SENT', 'Envoyée'), ('PENDING', 'En attente')], default='PENDING', max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.account')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
